name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      uses: actions/checkout@v2
      uses: actions/checkout@v2
    - name: hexfile
      run: gcc 3_Implementation/ultrasonicsensor.hex
    - name: ino file
      run: ultrasonicsensor.hex
    - name: simuleide file
      run: ultrasonicsensor project.simu
